[project]
name = "project6"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Dan Naiger", email = "dannitzhak@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
project6 = "project6:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
